# REF: https://github.com/SillyTavern/SillyTavern/blob/13099c43a93afc23a7fb7544e53024e188fbe537/default/config.yaml

whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
  - char-archive.evulid.cc

# Expose ST so Railway can forward it to a domain
listen: true
port: ${PORT}
# We'll be using multi-user instead
whitelistMode: false
# Enable multi-user
enableUserAccounts: true
# Whether to hide user list or not
enableDiscreetLogin: ${SILLYTAVERN_DISCREET_LOGIN}
# For some reason ST wouldn't let me expose ST if this is set to false
securityOverride: true
